server.port: 20203
spring.cloud.gateway.routes:
  - id: friendModule
    uri: http://juliendudek.synology.me:20204/
    predicates:
      - Path=/friends/**
    filters:
      # Add following Filter Response header in order to remove duplicates CORS value for a Http Header
      - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
  - id: postModule
    uri: http://juliendudek.synology.me:20205/
    predicates:
      - Path=/posts/**
    filters:
      # Add following Filter Response header in order to remove duplicates CORS value for a Http Header
      - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE

spring:
  boot:
    admin:
      client:
        url: http://juliendudek.synology.me:20201/
        instance:
          service-base-url: http://juliendudek.synology.me:20203/
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://juliendudek.synology.me:20206"
            allowedMethods: "*"
            allowedHeaders: "*"
application:
  current-profile: prod
