server.forward-headers-strategy: native
management.endpoints.web.exposure.include: '*'
# SECU
auth0:
  audience: social-network-M1S2MIII-mjp
  domain: jdkiii.eu.auth0.com
# BDD
spring:
  r2dbc:
    username: m1s2TpProg
    password: l@Cath0M1s2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/

